### ISSUE TITLE
WCL Not Recognized

### ISSUE THREAD

**Issue by eltoneo** [intbeam/watcom-vscode#6]
Re: Linux install
Hi,
vscode trapped the following error:
& $command $wclArguments

The term ‘wcl" is not recognized as a name of
a cmdlet, function, script file, or executable
program. Check the spelling of the name, or if
a path was included, verify that the path is
correct and try again.
******
please help resolve . . . .

**Comment by eltoneo** [comment]
/usr/bin/watcom/binl added to /etc/profile
~SOLVED~

**Comment by intbeam** [comment]
Ah excellent.. Thanks for reporting, I'll try to fix things going forwards.. Re-upping my focus
